# Generated by Django 5.2.11 on 2026-02-19 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='task',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='EmployeeProfile',
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
