# Generated by Django 5.2.11 on 2026-02-20 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_module', '0002_attendance_is_verified_attendance_verified_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachment_file',
            field=models.FileField(blank=True, help_text='File uploaded by HR when creating task', null=True, upload_to='task_attachments/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='submission_file',
            field=models.FileField(blank=True, help_text='File uploaded by employee when submitting task', null=True, upload_to='task_submissions/'),
        ),
    ]
