# Generated by Django 5.2.10 on 2026-02-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_module", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="is_employee",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="date_of_joining",
            field=models.DateField(auto_now_add=True),
        ),
    ]
